### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by gauthamzz**

### CODE REVIEW

**Comment by hackerkid** [comment]
Follow the format. 

https://github.com/hackerkid/Mind-Expanding-Books/blob/master/CONTRIBUTING.md

**Comment by gauthamzz** [comment]
update fiction adding to kill a mocking bird .

**Comment by hackerkid** [comment]
@gauthamzz  Send a new pull request. Your commit should also follow the format.

**Comment by gauthamzz** [comment]
k

**Pull request closed without merging**
