### PR TITLE
Add Atomic Habits

### PR DESCRIPTION
**Pull request by Prathamesh404**
## In this pull request
- [x]  I am adding a new book.
- [ ]  I am adding a new category
- [ ] Removing a book

## Adding new book
* The book I am adding is Atomic Habits by James Clear
* I am adding this book to Philosophy and Psychology  section.
* I have read this book 2 times.
* I think this book deserves to be in this list because you a clear gist of things which queues in our daily routine triggers habit formation. It also roots into path of less resistance to create clutter free environment. Breaking down book into four laws and other additional material on website such as cheat-sheet can make it more than just another self help book.

### CODE REVIEW

**Comment by hackerkid** [comment]
Please add the book in correct position according to goodreads rating. Thanks!

**Comment by Prathamesh404** [comment]
Hey are you planning to create a static website which can redirect to Amazon or Goodreads. Maybe host it on the github pages. Just a thought. Thanks for the heads up

**Comment by hackerkid** [comment]
That was something I had in mind. Didn't get the time to do it yet.

**Comment by Prathamesh404** [comment]
Well in the sea of resources some really filtered data about things works
as an essential resource.

**Comment by hackerkid** [comment]
@Prathamesh404 Created https://github.com/hackerkid/Mind-Expanding-Books/issues/178

**Pull request merged**
