### PR TITLE
Smaller sidebar, visible header

### PR DESCRIPTION
**Pull request by thedudio**
- The sidebar and the contained links were so large, that it was easy to misclick on a topic, when you just wanted to make sure the current window is in focus. Now the sidebar is only as big as the content.
- The header of the site was not visible. Now it is.

### CODE REVIEW

**Comment by thedudio** [comment]
Sorry for the merge conflict, but it was easy to resolve. I forgot to update my master before the changes.

**Comment by hackerkid** [comment]
@thedudio The changes looks great. Can you rebase on top of master?

**Comment by thedudio** [comment]
Hi @hackerkid i recieved an email, where you ask me about rebasing with your master. But now i cannot see the comment here. Did you delete it? I resolved all conflicts, so a rebase is not required any longer. 
Please tell me if I missed something else.

**Comment by hackerkid** [comment]
Merged. Thanks a lot on working on this @thedudio

**Pull request merged**
