### PR TITLE
Update for book cover of "The Discoverers"

### PR DESCRIPTION
**Pull request by Shweta200126**
Fix: #371

## In this pull request 
- [ ]  I am adding a new book.
- [ ]  I am adding a new category
- [X] Replacing a book cover

##Book name:
- The Discoverers by Daniel J. Boorstin
- Removed the jpg file of wrong book cover
- Replaced it with correct book cover's jpg link

### CODE REVIEW

**Comment by hackerkid** [comment]
Thank you for working on this. Merged thanks :)

**Comment by Shweta200126** [comment]
@hackerkid  sorry to disturb but do you know how much long will it take for it to be shown in the website? 
Also it says deploy failed, do you have any idea .....

**Comment by hackerkid** [comment]
@Shweta200126 No problem. hmm. The deploy was sucessfull in your PR so it is kind of weird that it failed in the master branch. The reran the build and it failed again. Will investigate what is the issue.

**Comment by Shweta200126** [comment]
@hackerkid I tried to see what the problem may have been there:
It shows in build> Run Python Script:-
GOODREADS_PUBLIC_API_KEY = ***
NameError: name '***' is not defined
Error: Process completed with exit code 1.
[https://github.com/hackerkid/Mind-Expanding-Books/runs/2743893572?check_suite_focus=true](https://github.com/hackerkid/Mind-Expanding-Books/runs/2743893572?check_suite_focus=true)
Does this help?

**Comment by hackerkid** [comment]
@Shweta200126 That GitHub action is used for fetching details of books from goodreads API and all. It is not used for building the website. The website is built in Netlify. Here is the log of the build.

https://app.netlify.com/sites/mind-expanding-books/deploys/60b9f85147139d042494e3c7

From the log it looks like the build failed because of some depedency issues

https://app.netlify.com/sites/mind-expanding-books/deploys/60b9f85147139d042494e3c7

I think updating the dependencies might likely fix the issue.

**Comment by hackerkid** [comment]
Looks like this is the exact issue.

> 3:25:18 PM: error meros@1.1.4: The engine "node" is incompatible with this module. Expected version ">=12". Got "10.24.1"

I tried changing the base image in Netlify from 16.04 to 20.04, but I still got the same error. I think to make this work we should make sure that the nodeversion is >=12 somehow.

**Comment by hackerkid** [comment]
Looks like you can easily tell netlify what Node version to install by setting up the NODE_VERSION environment variable

https://docs.netlify.com/configure-builds/manage-dependencies/#node-js-and-javascript

Let me try rebuilding with another version.

**Comment by hackerkid** [comment]
That error is now gone and is replaced with a new error
https://app.netlify.com/sites/mind-expanding-books/deploys/60bd19364f3fc77305a029f5

**Comment by Shweta200126** [comment]
Hey I don't really understand all this but I hope it gets right.

**Pull request merged**
