### PR TITLE
added the alchemist by paulo Coelho

### PR DESCRIPTION
**Pull request by Jobin-S**
(todo: please remove this todo and the sections you did not check below before you make your pull request.
If you are unsure, please check other PRs like this one: https://github.com/hackerkid/Mind-Expanding-Books/pull/207#issue-377268434)

## In this pull request 
- [x]  I am adding a new book.

## Adding new book
* The book I am adding is The Alchemist
* I am adding this book to fiction section.
* I have read this book 2+ times.
* I think this book deserves to be in this list because this book gives positive mind to do things.

### CODE REVIEW

**Comment by Jobin-S** [comment]
is there any issue in this PR. please let me know

**Comment by hackerkid** [comment]
@Jobin-S The PR looks fine. I am actually holding back on merging books that have less than 4 rating for now until I get more feedback. I have read the Alchemist, but I didn't find it super impressive. But I read a Malayalam version so it cannot do much justice to the original. So waiting for feedback from others.

**Comment by Jobin-S** [comment]
okay, the book is awesome

**Comment by hackerkid** [comment]
@Jobin-S Can you fix the merge conflicts? I would merge it after that.

**Comment by Jobin-S** [comment]
i have cleared the conflict

**Comment by hackerkid** [comment]
@Jobin-S See https://github.com/hackerkid/Mind-Expanding-Books/pull/268/files. Now the PR don't have the book.

**Comment by hackerkid** [comment]
I am going through all the old PRs in the repo. I might have closed this because of one of the following
* There is no description.
* The book is not added by decreasing goodreads rating.
* Have lot of merge conflicts

Sorry for closing the PR. But feel free to create a new one!

**Pull request closed without merging**
