### PR TITLE
CLI to order, reformat and get external data

### PR DESCRIPTION
**Pull request by geritol**
Created to solve issue #91

### CODE REVIEW

**Comment by enthusiast94** [comment]
Does this also sort the books by average rating? If yes, this could also resolve [this issue](https://github.com/hackerkid/Mind-Expanding-Books/issues/102).

**Comment by geritol** [comment]
yes, if you take a look at the code, you can specify that which property of the book you want to sort on on the CLI, the default is the GoodReads rating for it.

**Comment by hackerkid** [comment]
@geritol Huge thanks for building this. I used the tool to update the list and pushed the new format. Some comments.
* Some books had 0.00 rating after using the tool. I ran the tool only once so I am not sure it may occur again. I fixed them in https://github.com/hackerkid/Mind-Expanding-Books/commit/23ad4fac466e0508bc397d0caf9a98f4c0815097
* Some books don't have year. I guess that is an issue with Goodreads API. We can manually add year for them. But if we run the tool again the tool should preserve the year present in the list if year data is not present in the API.
* I think we should probably have some sort of mechanism to keep the list updated which will run the tool in travis and update the README.md during the pull request. Or we can mention in contributing.md to run the tool after they add a new book. Or maybe I can run this tool every month. What do you think?

**Comment by geritol** [comment]
The 0 rating should be only if we get nothing form goodreads. Will check what the response was for these books if I will have time.
If the book has a rating the script will skip the part where it queries goodreads so this should be fine.
Yes probably autorunning it should be an option, I do not know where to put the API key then (should not be public to prevent abuse)

**Comment by geritol** [comment]
Yes, the issue is that I query by title but googreads sometimes returns a different book. Eg. for Richard Branson's book, we get the Japanese version, which has no ratings (Losing My Virginity: The Autobiography [In Japanese Language])

**Pull request merged**
