### PR TITLE
Add books that blowed my mind for C and Java | Hacktoberfest

### PR DESCRIPTION
**Pull request by PARAG00991**
Added two advanced level books for 2 popular programming languages **C** and **Java**.
Referencing issue #29  (Hacktoberfest)

### CODE REVIEW

**Comment by hackerkid** [comment]
I am not sure this repository is the right place for these books.

**Comment by PARAG00991** [comment]
@hackerkid ,  As the repository contains all the mind expanding books and hence IMHO these books fit right in the category of programming languages because of the advanced and deep level concepts given in the book.

**Comment by wowi42** [comment]
👍

**Comment by hackerkid** [comment]
No longer a valid category.

**Pull request closed without merging**
