### PR TITLE
Add 'The Alchemist' fictional book

### PR DESCRIPTION
**Pull request by Darepapi**
Hey there!
I just added The Alchemist because it teaches you that everything you want and need is close to home. Take chances. Follow your  personal legacy!!

### CODE REVIEW

**Comment by hackerkid** [comment]
@Darepapi Thanks for working on this. But there is already a PR open for this book. Maybe you can add your comment on why we should add the book in the list there.
https://github.com/hackerkid/Mind-Expanding-Books/pull/268

**Comment by Darepapi** [comment]
Hello friend...

Sorry I wasn't aware a PR was opened for the book already.

I'd like you add the book because It is very inspiring and a life changing book depending on "how deep you relate to it". 

A good book to recommend any day, any time.

Thanks!

**Comment by hackerkid** [comment]
@Darepapi Cool. I would merge the original PR then.

**Comment by Darepapi** [comment]
That'd be great!

**Pull request closed without merging**
