### PR TITLE
better responsive for bookcard

### PR DESCRIPTION
**Pull request by arifsetyo21**
1. better responsive for bookcard

## In this pull request 
- [x]  Repair responsive for this bookcard   #236 .
Please check my PR @hackerkid thanks very much

### CODE REVIEW

**Comment by hackerkid** [comment]
@arifsetyo21 Can you fix the merge conflitcs?

**Comment by arifsetyo21** [comment]
Yes i can, but wait little hours

**Comment by hackerkid** [comment]
@arifsetyo21 Maybe try creating another PR on a fresh branch off the latest master?

**Comment by hackerkid** [comment]
I am going through all the old PRs in the repo. I might have closed this because of one of the following
* There is no description.
* The book is not added by decreasing goodreads rating.
* Have lot of merge conflicts

Sorry for closing the PR. But feel free to create a new one!

**Pull request closed without merging**
