### PR TITLE
eslint fixes

### PR DESCRIPTION
**Pull request by bahdotsh**
##In this PR I have fixed the linting issues

### CODE REVIEW

**Comment by hackerkid** [comment]
@bahdotsh Maybe we should add a check for this in CI using GitHub actions. That seems like the correct long term fix. Want to work on that?

**Comment by bahdotsh** [comment]
> @bahdotsh Maybe we should add a check for this in CI using GitHub actions. That seems like the correct long term fix. Want to work on that?

Yes, let's do that.

**Comment by hackerkid** [comment]
@bahdotsh Do you want to try that?

**Comment by bahdotsh** [comment]
@hackerkid Yes. I haven't done anything with GitHub actions, so may need your help too.

**Comment by hackerkid** [comment]
@bahdotsh Sure. Do give it a try. Its very straightforward. Search for GitHub action CI examples.

**Pull request closed without merging**
