### PR TITLE
Updated styles for bookcard

### PR DESCRIPTION
**Pull request by xevenheaven**
This is in relation to issue https://github.com/hackerkid/Mind-Expanding-Books/issues/244.

Changes made:
* The Goodreads image has been included
* Bookcard styles have been updated

| Before | After |
| ------ | ----- |
| image | image |

### CODE REVIEW

**Comment by hackerkid** [comment]
This looks amazing. Merged!

@xevenheaven If you are interested, can you take a look at why some book covers are displayed incorrectly? I think it was a regression that was introduced in the last 2 days.

**Comment by xevenheaven** [comment]
Thanks @hackerkid - do you mind if this PR is label with `hackertobest-accepted`? 😄 

And sure, let me see what I can do for the book covers!

**Comment by hackerkid** [comment]
> Thanks @hackerkid - do you mind if this PR is label with hackertoberfest-accepted? smile

Done! Is the label necessary for counting towards Hacktoberfest? So that I can add the label in other PRs as well.

> And sure, let me see what I can do for the book covers!

Thanks!

**Comment by hackerkid** [comment]
> @xevenheaven If you are interested, can you take a look at why some book covers are displayed incorrectly? I think it was a regression that was introduced in the last 2 days.

I think the issue is not there anymore in production. Must have been some caching issue. Before covers of books were getting shuffled randomly.

**Comment by xevenheaven** [comment]
I'm not entirely sure how the new hacktoberfest rules are played out @hackerkid 😅 , but here is what I read:
>Your pull requests will count toward your participation if they are in a repository with the hacktoberfest topic, and once they have been merged, approved by a maintainer or labeled as hacktoberfest-accepted.

Got you about the book covers - if there are other issues that no one is working on, let me know! Thanks 😄

**Comment by hackerkid** [comment]
@xevenheaven If you are interested you can work on creating unique page(eg http://books.vishnuks.com/book/sapiens) for each book similar to how we generate categories. The page would have name, description, cover etc of the book. Later on, we can also build some kind of functionality to show similar books. But that can be a separate issue (which you or someone else interested can work on).

**Comment by hackerkid** [comment]
Also the book cover issue is still there in the latest deploy

Screenshot from 2020-10-12 17-32-11

**Comment by xevenheaven** [comment]
I'll look into the bug with the book cover first, @hackerkid 😄 👍

**Pull request merged**
