### PR TITLE
Adds art as a category; Adds three book to art category;

### PR DESCRIPTION
**Pull request by DBozhinovski**
## In this pull request 
- [x]  I am adding a new book.
- [x]  I am adding a new category
- [ ] Removing a book

## Adding new book
* The book I am adding is Drawing on the right side of the brain
* I am adding this book to Art section.
* I have read this book 3 times.
* I think this book deserves to be in this list because it has a very special way of destroying the prejudice that one needs some incredible talent to be a good artist / painter. However, calling it just a book about art would be underselling it - the book has a lot on how we thing, how we perceive and many other psychological aspects of a human character that can make us put ourselves in proverbial boxes without realizing hidden talents we might have.

## Adding new book
* The book I am adding is Steal like an artist
* I am adding this book to Art section.
* I have read this book 4 times.
* I think this book deserves to be in this list because it helped me grow further in my artistic pursuits. It has a very interesting way of nailing down what creativity really is and that we all really live in a remix-heavy culture. It can be a liberating realization, especially if one is stuck in an artistic rut, so to speak.

## Adding new book
* The book I am adding is Show your work
* I am adding this book to Art section.
* I have read this book 2 times.
* I think this book deserves to be in this list because it really expands what Austin Kleon's previous book was about, but it focuses on being public with your work - with all the good, bad and ugly sides it brings. Ultimately, it makes you realize that you are likely your own worst critic and it's totally fine to ignore that discouraging inner voice most of the time.

## Add new category
* The category I am adding is Art
* The reason why I think this category should be there is because art as one of the oldest pursuits, can really help people grow (and I speak from experience on this one). It is very helpful to expand one's toolset and skills outside of their normal competencies because it also helps us improve our existing skills. Art and coding have a lot more in common that one realizes.
* - [x] I have added at least one book to this category

### CODE REVIEW

**Comment by hackerkid** [comment]
@DBozhinovski Thanks for working on this. You need to add the books in README.md. book.json is generated automatically. Feel free to also update the CONTRIBUTING.md in this pull request file if that was not clear before :)

**Comment by DBozhinovski** [comment]
@hackerkid Oops, sorry - I read that in reverse. Will handle that later today :+1:

**Comment by DBozhinovski** [comment]
Hopefully in the proper format now :)

**Comment by hackerkid** [comment]
This looks great. Merged. Thanks a lot :)

**Pull request merged**
