### PR TITLE
Adding a book

### PR DESCRIPTION
**Pull request by mRuggi**
## In this pull request 
- [x]  I am adding a new book.
- [ ]  I am adding a new category
- [ ] Removing a book

## Adding new book
* The book I am adding is The Little Prince
*I am adding this book to Education section.
*I have read this book 3 times.
*I think this book deserves to be in this list because it is very educational

### CODE REVIEW

**Comment by mRuggi** [comment]
i think this time i made it right

**Comment by hackerkid** [comment]
Can you add a commit to get rid of `?ac=1&from_search=true&qid=Ot5tWt8TKY&rank=1` from Goodreads URL?

**Comment by mRuggi** [comment]
done!

**Comment by hackerkid** [comment]
Thanks a lot for working on this. Merged thanks :)

**Pull request merged**
