### PR TITLE
Improve bookcard UI responsiveness

### PR DESCRIPTION
**Pull request by paymin**
I would like to improve your UI responsiveness so it can fit to any device screen width.
ezgif com-video-to-gif

I also want to modified the sidebar to be responsive for the next PR.

### CODE REVIEW

**Comment by TriinK** [comment]
Maybe also add a hamburger menu in mobile view?

**Comment by hackerkid** [comment]
> Maybe also add a hamburger menu in mobile view?

Yes. We should improve the mobile view. It's less than ideal at the moment. @paymin Can you take care of that as well?

**Comment by paymin** [comment]
Yes, it sounds good. I'll take care of that

**Comment by paymin** [comment]
hey @hackerkid i have just added the 🍔 menu

ezgif com-video-to-gif(1)

**Comment by hackerkid** [comment]
@paymin These changes look great. Can you take care of the merge conflicts as well? I will merge right after that.

**Comment by paymin** [comment]
@hackerkid sure

**Comment by hackerkid** [comment]
@paymin Have you fixed conflicts and rebased on top of master?

**Comment by paymin** [comment]
I have just resolved the conflict again, i merger my code to the master. no need to rebase

**Comment by paymin** [comment]
I've just resolved the conflict, it's now run smoothly with your latest master. Please tell me if I missed something else.

**Comment by hackerkid** [comment]
@paymin I am really sorry. Some more conflicts came while I was merging other PRs. Can you fix the conflicts one last time.

**Comment by hackerkid** [comment]
@paymin Is this ready for review? The save to reading list button seems to be missing.
https://deploy-preview-231--mind-expanding-books.netlify.app/

**Comment by paymin** [comment]
image

**Comment by hackerkid** [comment]
@paymin  Thanks a lot for working on this. Merged thanks :)

**Comment by kalokma** [comment]
Build ID (e.g., RP1A.200720.012). Indicates AOSP bas

**Pull request merged**
