### PR TITLE
changes to the sidebar, cards and footer

### PR DESCRIPTION
**Pull request by palak199**
## In this pull request 
- [X]  I am replacing the existing footer with a sticky footer so that when scrolling is deep the footer doesn't seem to be lost, also the previous footer was getting hidden behind the sidebar .
- [X]  I am adding a new Read More button, currently it has no href but earlier the truncation gave bad UX
- [X] I am adding responsiveness to the cards and sidebar removing the hardcoded inline styles

### CODE REVIEW

**Comment by palak199** [comment]
sir kindly review it and tell if I must do any other changes.

**Comment by hackerkid** [comment]
@palak199 Thanks a lot for working on this!

I tested this using automatic deploy generated at https://deploy-preview-237--mind-expanding-books.netlify.app/

The Read more button does not seem to be doing anything when I click on it. Also, we can replace the Read more button with text. The button is standing out too much.

Also I don't think we need the footer to be shown like that. It does not have any useful information in it. So its not that super useful to show it always.

**Comment by palak199** [comment]
@hackerkid I didn't put the href in the button because i wanted to confirm do you want to display the whole text on button click there itself or lead it to a new card which displays only that individual book's information. The truncation is leaving an ugly impact.
Let me know your thought about it, and then I ll modify and thanks for reviewing.

**Comment by hackerkid** [comment]
> I didn't put the href in the button because i wanted to confirm do you want to display the whole text on button click there itself or lead it to a new card which displays only that individual book's information. 

Showing it in a new page with only the book information would be pretty cool. For that you need to generate pages for all the books like we do for categories. How about expand the book description for now and show it in a new page as a followup PR?

**Comment by palak199** [comment]
Please checkout now, I have implemented the show more and less button and tested that it is working fine.

**Comment by hackerkid** [comment]
@palak199 Awesome. Can you get rid of the sticky footer. Rest looks good to me :)

**Comment by palak199** [comment]
@hackerkid i have commented out the footer, in case in future you need, you can use it! hope it works

**Comment by hackerkid** [comment]
@palak199 Than
Thanks a lot for working on this. Merged thanks :)

Can you make the book cover stay fixed when you click on expand as a followup PR?

**Pull request merged**
